apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "int-mastodon.fullname" . }}
  labels:
    {{- include "int-mastodon.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "int-mastodon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "int-mastodon.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "int-mastodon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      priorityClassName: "{{ .Values.priority.class }}"
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: API_PORT
              value: "{{ .Values.service.port }}"
            - name: API_WRITER_BACKOFF
              value: "{{ .Values.api.writer.backoff }}"
            - name: API_WRITER_URI
              value: "{{ .Values.api.writer.uri }}"
            - name: API_ACTIVITYPUB_HOST
              value: "{{ .Values.api.activitypub.host }}"
            - name: API_ACTIVITYPUB_URI
              value: "{{ .Values.api.activitypub.uri }}"
            - name: API_EVENT_TYPE
              value: "{{ .Values.api.event.type }}"
            - name: LOG_LEVEL
              value: "{{ .Values.log.level }}"
            - name: API_MASTODON_SEARCH_LIMIT
              value: "{{ .Values.mastodon.search.limit }}"
            - name: API_MASTODON_COUNT_MIN_FOLLOWERS
              value: "{{ .Values.mastodon.count.min.followers }}"
            - name: API_MASTODON_COUNT_MIN_POSTS
              value: "{{ .Values.mastodon.count.min.posts }}"
            - name: API_MASTODON_CLIENT_USER_AGENT
              value: "{{ .Values.mastodon.client.userAgent }}"
            - name: API_MASTODON_ENDPOINT_PROTOCOL
              value: "{{ .Values.mastodon.endpoint.protocol }}"
            - name: API_MASTODON_ENDPOINT_ACCOUNTS
              value: "{{ .Values.mastodon.endpoint.accounts }}"
            - name: API_MASTODON_ENDPOINT_SEARCH
              value: "{{ .Values.mastodon.endpoint.search }}"
            - name: API_MASTODON_CLIENT_HOSTS
              valueFrom:
                secretKeyRef:
                  name: "{{ include "int-mastodon.fullname" . }}-client"
                  key: hosts
            - name: API_MASTODON_CLIENT_TOKENS
              valueFrom:
                secretKeyRef:
                  name: "{{ include "int-mastodon.fullname" . }}-client"
                  key: tokens
            - name: API_QUEUE_URI
              value: "{{ .Values.queue.uri }}"
            - name: API_QUEUE_INTERESTS_CREATED_BATCH_SIZE
              value: "{{ .Values.queue.interestsCreated.batchSize }}"
            - name: API_QUEUE_INTERESTS_CREATED_NAME
              value: "{{ .Values.queue.interestsCreated.name }}"
            - name: API_QUEUE_INTERESTS_CREATED_SUBJ
              value: "{{ .Values.queue.interestsCreated.subj }}"
            - name: API_QUEUE_INTERESTS_UPDATED_BATCH_SIZE
              value: "{{ .Values.queue.interestsUpdated.batchSize }}"
            - name: API_QUEUE_INTERESTS_UPDATED_NAME
              value: "{{ .Values.queue.interestsUpdated.name }}"
            - name: API_QUEUE_INTERESTS_UPDATED_SUBJ
              value: "{{ .Values.queue.interestsUpdated.subj }}"
            - name: API_QUEUE_SRC_SSE_BATCH_SIZE
              value: "{{ .Values.queue.sourceSse.batchSize }}"
            - name: API_QUEUE_SRC_SSE_NAME
              value: "{{ .Values.queue.sourceSse.name }}"
            - name: API_QUEUE_SRC_SSE_SUBJ
              value: "{{ .Values.queue.sourceSse.subj }}"
            - name: API_TOKEN_INTERNAL
              valueFrom:
                secretKeyRef:
                  key: "{{ .Values.api.token.internal.key }}"
                  name: "{{ .Values.api.token.internal.name }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            grpc:
              port: {{ .Values.service.port }}
            timeoutSeconds: 10
          readinessProbe:
            grpc:
              port: {{ .Values.service.port }}
            timeoutSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "int-mastodon.name" . }}
